language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

before_cache: rm -rf $HOME/.m2/repository/fr/layer4

branches:
  only:
    - master
    # Build tags that match this regex in addition to building the master and dev branches.
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
