= HHSL
Vincent Devillers <https://github.com/treydone[@treydone]>;
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-org: https://github.com/treydone
:uri-repo: {uri-org}/hhsl
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE

image:https://travis-ci.org/Treydone/hhsl.svg?branch=master[link=https://travis-ci.org/Treydone/hhsl]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.layer4.hhsl%3Ahhsl&metric=alert_status[link=https://sonarcloud.io/dashboard?id=fr.layer4.hhsl%3Ahhsl]
image:https://sonarcloud.io/api/project_badges/measure?project=fr.layer4.hhsl%3Ahhsl&metric=reliability_rating[link=https://sonarcloud.io/dashboard?id=fr.layer4.hhsl%3Ahhsl]

HHSL allows you to easily connect to multiple Hadoop clusters by downloading the rights clients,
settings all the environment variables and preparing the -defaults.xml/-site.xml files.

HHSL has been developed by Hadoop sysadmin and developers, dealing with multiple, or even one, clusters,
who don't want to do the boring stuff of configuring all the clients like HDFS, HBase and others on every clusters.
This tool aims to easily switch from one cluster to an other, and is a defacto adapted tool for team managing multiple clusters.


== Requirements

HHSL works on Linux, macOS and Windows and requires:

* Java (1.8+)

== Installation

* Download the tarball and just unzip it.
* Optional: change your PATH environment variable

// TODO offer some curl | bash option

== How to

Check the version:

 > hhsl info
 -----------------------------------------------------------------------------
  HHSL
  Version: 0.3-SNAPSHOT
  Commit: 181c0a9e0415efe0fd01b3cc088f9e97ed78845a ()
  Build: 2018-11-15T07:29:44+0000
  Terminal
  - size: Size[cols=77, rows=30]
  - class: PosixSysTerminal
  - type: xterm-256color
  - attributes: Attributes[lflags: echoke echoe echok echo echoctl isig icanon, iflags: brkint icrnl ixon ixany imaxbel iutf8, oflags: opost onlcr, cflags: cs6 cs7 cs8 cread hupcl, cchars: eof=^D eol=<undef> eol2=<undef> erase=^? werase=^W kill=^U reprint=^R intr=^C quit=^\ susp=^Z dsusp=<undef> start=^Q stop=^S lnext=^V discard=^O min=1 time=0 status=<undef>]
 -----------------------------------------------------------------------------

 > hhsl init
 password: ****
 retype password: ****

By initiating the database, a local registry is defined. A registry holds the references to clusters.
HHSL can refer multiple registries. By default, a local registry is defined, and for each commands
using a registry, that local registry is used.

You can then add a cluster. For instance, we add a cluster managed by Ambari, available at http://ambari:8080 and named PROD-HDP3.0:

```
hhsl add cluster local ambari PROD-HDP3.0 http://ambari:8080
> user:
> password:
```

Verify that the cluster has been added:

```
hhsl list cluster

┌────────┬───────────┬──────┬──────────────────┐
│Registry│Name       │Type  │URI               │
├────────┼───────────┼──────┼──────────────────┤
│local   │PROD-HDP3.0│ambari│http://ambari:8080│
└────────┴───────────┴──────┴──────────────────┘
```

Now use it:

```
hhsl use PROD-HDP3.0
# or hhsl use cluster PROD-HDP3.0
```

The command 'use' download the missing clients, prepare the environment variables and
render the configuration files. You can check them by using the 'env' command in Linux for instance:

```
env
....
HADOOP_HOME=/xxxxx
SPARK_HOME=/xxxx
HBASE_HOME=/xxxxx
```

Also have a look on configuration files:
```
cat
```

// TODO Banners

== About security

HHSL uses a secure storage in order to manage secrets and credentials for registries and resolvers.
Most HHSL resolvers require credentials to interact with a third-party service managing their configuration: Ambari for Hortonworks, Cloudera Manager for Cloudera...
HHSL has a simple mechanism to protect secrets: it use by default an implementation of a secure storage based on a H2 encrypted database (see plugins/local-store).
Therefor, if you want to use HHSL, you need to specify a key to unlock the store. The first you use HHSL, you will be prompted to enter the root password.

With HHSL, you can unlock the store in 3 ways with the ```--unlock``` options:
- direct password
- file, if you enter an option starting with "file://..."
- prompt, if you enter ```@prompt```

The preferred way to unlock the secured store is @prompt, which asks the user to enter the root password:

 hhsl ... --unlock @prompt
 Root password:>

For background process or automatic filling of the root password, you can use the file or direct password options:

 hhsl ... --unlock <some password>
 hhsl ... --unlock file:///...

Be aware that your commands will be store in the history of your shell if you use direct password...
The file option allows you to use a file containing the root password. Ensure to protect this file with some restrictions (chown+chmod 700)

== Man

**install**

**init**

**env**

**set env**

**get env**

// TODO

== Architecture

HHSL store all its data by default in ~/.hhsl (will be configurable in future releases, see Roadmap)

```
~/.hhsl


```
//TODO

**archives**: contains all the binaries, compressed and uncompressed.

**confs**: contains all the generated configurations done when the command 'use cluster ...' is called.
confs is a multi level directories structured like this:
registryconnection id > cluster id > service name

**db**: the content of the local db

Since both /archives and /confs contains generated content, these directories can be wiped without fear, their content will be regenerated on the next call to 'use cluster ...'

== Configuration

=== Binaries

// TODO
Not currently implemented

.Available properties for binaries configuration
[width="100%"]
|===
|Property |Default value |Mandatory |Description

|binaries.check
|true
|no
|

|===

=== URLs

// TODO
Not currently implemented

.Available properties for URL configuration
[width="100%"]
|===
|Property |Default value |Mandatory |Description

|url.mirror.apache.enabled
|true
|yes
|

|url.mirror.apache
|http://www.apache.org/dyn/closer.cgi/
|yes
|

|url.dist.apache
|https://dist.apache.org/repos/dist/release/
|no
|Used when ```mirror.enabled``` is false

|url.signature.apache
|https://dist.apache.org/repos/dist/release/
|yes if
|Used when ```mirror.enabled``` is false

|===

=== HTTP

.Available properties for HTTP configuration
[width="100%"]
|===
|Property |Default value |Mandatory |Description

|http.socket.timeout
|30000
|yes
|Socket timeout

|http.connect.timeout
|30000
|yes
|Connect timeout

|http.insecure
|false
|yes
|Allow insecure SSL connections and transfers.

|===

=== Proxy

HHSL use external resources hosted on mirrors, like the Apache mirrors, and many others.
You may need to use a proxy if your company or your private network settings requires some configuration.
In HHSL, you can to change these properties:

.Available properties for proxy configuration
[width="100%"]
|===
|Property |Default value |Mandatory |Description

|proxy.enabled
|false
|no
|Enabled proxy configuration

|proxy.host
|-
|*yes*
|

|proxy.port
|-
|*yes*
|

|proxy.auth.type
|none
|*yes*
|Possible values: none, ntlm, basic

|proxy.auth.ntlm.user
|-
|*yes* if ```proxy.auth.type``` is ntlm
|

|proxy.auth.ntlm.password
|-
|*yes* if ```proxy.auth.type``` is ntlm
|

|proxy.auth.ntlm.domain
|-
|*yes* if ```proxy.auth.type``` is ntlm
|

|proxy.auth.basic.user
|-
|*yes* if ```proxy.auth.type``` is basic
|

|proxy.auth.basic.password
|-
|*yes* if ```proxy.auth.type``` is basic
|
|===

== Build

=== Build a distribution from sources

On the root project, just run:

 mvn clean package

At the end, you should the final archive in cli/target/cli-X.X.X.tar.gz

=== Release

 mvn --batch-mode release:clean release:prepare -Dtag=v0.1 -DreleaseVersion=0.1 -DdevelopmentVersion=0.2-SNAPSHOT
 mvn release:perform

Or, skipping the tests

 mvn --batch-mode release:clean release:prepare -Dtag=v0.1 -DreleaseVersion=0.1 -DdevelopmentVersion=0.2-SNAPSHOT -DskipTests -DskipITs -Dmaven.javadoc.skip=true -Darguments="-Dmaven.javadoc.skip=true -DskipTests -DskipITs"

Force update the version:

 mvn --batch-mode release:update-versions -DautoVersionSubmodules=true -DdevelopmentVersion=0.4-SNAPSHOT
 
== FAQ

=== I need to use a proxy

See Proxy

Example for proxies without authentication

 hhsl set env proxy.enabled true
 hhsl set env proxy.host leproxy.intern
 hhsl set env proxy.port 8888

Example for proxies requiring basic authentication

 hhsl set env proxy.enabled true
 hhsl set env proxy.host leproxy.intern
 hhsl set env proxy.port 8888
 hhsl set env proxy.auth.type basic
 hhsl set env proxy.auth.basic.user myuser
 hhsl set env proxy.auth.basic.password lepassword

Example for proxies requiring NTLM authentication

 hhsl set env proxy.enabled true
 hhsl set env proxy.host leproxy.intern
 hhsl set env proxy.port 8888
 hhsl set env proxy.auth.type ntlm
 hhsl set env proxy.auth.ntlm.user myuser
 hhsl set env proxy.auth.ntlm.password lepassword
 hhsl set env proxy.auth.ntlm.domain INTERN

=== My service is not managed by HHSL

HHSL manages some services (HDFS, HBASE and many others). If your service is not yet managed by HHSL, just create an implementation of fr.layer4.hhsl.binaries.ClientPreparer. See fr.layer4.hhsl.binaries.HdfsClientPreparer for an example.

=== How is security managed in HHSL?

Kerberos authentication is not yet managed by HHSL. This feature will be added soon.

== Roadmap

* Allow to use a custom path for HHSL instead of the default ~/.hhsl via the configuration
* Allow to use private binaries repositories instead of default Apache mirrors
* Allow to skip integrity of files (specially in case of private repos)
* Add option to skip winutils for Hadoop
* Add security (Kerberos) switch
* Manage other clients (Cassandra, MongoDB...)
* Add MapR
* Add a Offline Mode
* Force a version of a client for a cluster

== Contributions

Contributions are welcome! To submit a pull request you should fork the project repository, and make your change on a feature branch of your fork.

== License

Copyright (C) 2012-2018 Vincent Devillers, and the individual contributors to HHSL.
Use of this software is granted under the terms of the MIT License.

See the {uri-license}[LICENSE] for the full license text.

=== Update third parties license file

Update the content of the file THIRD-PARTY.txt:

 mvn org.codehaus.mojo:license-maven-plugin:aggregate-add-third-party@aggregate-add-third-party

=== Update license header on files

Update licence header on files

 mvn org.codehaus.mojo:license-maven-plugin:update-file-header@update-file-header

== Authors

* Vincent Devillers
