---
spring:
  profiles: debug
logging:
  level:
    root: WARN
    fr.layer4.dek: DEBUG
    org.apache.http.wire: INFO
    org.apache.http: DEBUG

---
spring:
  profiles: runtime
logging:
  level:
    root: ERROR
    fr.layer4.dek: WARN
    org.apache.http.wire: INFO
    org.apache.http: WARN

---
spring:
  profiles:
    active: debug

  shell:
    script:
      enabled: false

git:
  version: "@project.version@"
  tags: "@git.tags@"
  branch: "@git.branch@"
  dirty: "@git.dirty@"
  remote:
    origin:
      url: "@git.remote.origin.url@"
  commit:
    id: "@git.commit.id@"
    abbrev: "@git.commit.id.abbrev@"
    describe: "@git.commit.id.describe@"
    describe-short: "@git.commit.id.describe-short@"
    user:
      name: "@git.commit.user.name@"
      email: "@git.commit.user.email@"
    message:
      full: "@git.commit.message.full@"
      short: "@git.commit.message.short@"
    time: "@git.commit.time@"
  build:
    user:
      name: "@git.build.user.name@"
      email: "@git.build.user.email@"
    time: "@git.build.time@"
